### ISSUE TITLE
Design the layout of the What-It-To-Do list

### ISSUE THREAD

**Issue by marneylaunder** [marneylaunder/what-it-to-do#1]
### Overview
_Here we go - first ticket for the project _🎉🎉🎉_ !  (Okay, back to work...)_ 

I want to have a good think about the layout of the tool before I cut any code. The tool should be intuitive enough for the user to get a quick overview of how many tasks they have pending per day/ how busy their day is looking 'at a glance'. 

The layout should also be neat enough that the user can see a broader view (for example, I like seeing a work-week list of tasks so I know what I can prioritise every day). 

Finally, tasks on the list should be able to be moved around (in different orders under a specific date, or moved out to different dates) - not sure how to imply this in the mockups, but something to keep in mind during the implementation. 

### Tasks

**1. Wireframe/ mockup**

- [x] Create a lo-fi wireframe/ mockup of the layout for the tool 
- [x] [Upload designs to this issue](https://miro.com/app/board/uXjVOZlg9Bo=/?invite_link_id=770989441905)

Design should include the following:

- [x] Utility/ text field to Add Tasks
- [x] Buttons to Edit/ Delete existing tasks
- [x] Button/ checkbox to close out completed tasks
- [x] Display of dates (couple different options here, including column per day, header per day with list down the page)
- [x] Have a work-week view of tasks 
- [x] Header/ filter to display different work weeks/ work months etc. 
- [x] **Flexible design to accomodate future features**

**2. Obtain feedback and update**

- [x] Get some feedback/ reviews from friends and family 
- [x] Mockup [final version]((https://miro.com/app/board/uXjVOZlg9Bo=/?invite_link_id=770989441905)) and upload so I can get cracking on the code

Final design to include:

- [x] Utility/ text field to Add Tasks
- [x] Buttons to Edit/ Delete existing tasks
- [x] Button/ checkbox to close out completed tasks
- [x] Headers and containers for To Do and Done tasks

### Feedback
Shout out to all the folks who provided some great feedback, quick summary of some feature requests and suggestions below:

**Timer-related features:**
-  "The above layout can include maybe different time blocks, I.e if I use pomodoro or deep work blocks of 40 mins, I can layout my to-do list for the day in those time blocks"
 - Include a timer for tracking tasks

**Ordering tasks:**
- "Order my list to be by priority like top 4 items per day up top then the rest follows"
- Order incomplete/ open tasks on top, and list completed/ closed tasks below to improve visibility of tasks that are still "to do"

**High-level timeline visuals:**
- "Would love to see the weekly view of this? If I select week view, what is the layout?"
- "Would like to include this on like a calendar type table each day/to show times so I can organise the daily tasks into what time of day I do them I.e like a calendar but without all the invites perhaps."
- Moving completed tasks to be displayed in a timeline

### Design/ Feedback Notes
I'm thinking to split this design up into an MVP/ proof-of-concept and add the above suggestions in future versions of this tool - organising by dates/ calendars seems like an ambitious stretch goal for now, but I really like the simple view of splitting up incomplete tasks and complete tasks under 2 seperate containers. 

**Components/ features to include in the MVP version:**
- Add/ Edit/ Delete/ View tasks
- Organise tasks under 2 headers: "To Do" and "Done"
- Have a way to move task orders around to get a visual representation of priority

### Helpful Links
- https://www.checklist.design/ - might come in handy
- List any resources I'm referring to here:
   - https://bootcamp.uxdesign.cc/creating-wireframes-and-low-fidelity-prototypes-in-figma-for-the-google-ux-course-326a7e11fa60
   - https://www.figma.com/blog/how-to-wireframe/

**Comment by marneylaunder** [comment]
Test
