### ISSUE TITLE
Build the What It To-Do HTML page

### ISSUE THREAD

**Issue by marneylaunder** [marneylaunder/what-it-to-do#2]
### Overview
_Time to dive into the code - call me Elliot Alderson  _🤖_ ..._

I've got a rough idea of the layout of my to-do list based on the design from [this ticket](https://github.com/marneylaunder/what-it-to-do/issues/1) - while it's still being reviewed by a few of my mates, I think I've ironed out the main structure enough to begin drafting up the HTML scaffold. 

### Scope
* HTML code only 
* Minimal styling (if any) - I just want to sort out the general layout of the page before jumping through to the next steps (styling and scripting)

### Tasks

**1. Build out the HTML layout**
Screenshot below with all the elements that need to be included: 

![Screen Shot 2021-12-22 at 6 41 29 pm](https://user-images.githubusercontent.com/96363563/147054413-6fdbb4ce-4b23-47f5-9a47-0676d6b8fbda.png)

- [x] Input field (text)
- [x] Add task button
- [x] Headers (h2) showing To Do and Done containers
- [x] Checkbox
- [x] Delete button (with icon)
- [x] Edit button (with icon)
- [x] Collapse button (with icon)
- [x] Expand button (with icon)

**2. Produce a HTML layout with all necessary elements**
This will serve more as a test/ proof-of-concept to show that I have all the elements I need before I begin adding styles to them. 

- [x] Add a screenshot of the HTML layout with the above elements incorporated:

![Screen Shot 2021-12-22 at 7 18 26 pm](https://user-images.githubusercontent.com/96363563/147059375-df1531b6-8c5e-4a2c-9e7d-fdbf3253a45e.png)

### Technical Notes
- The collapsible/ expandable buttons can added to the To Do and Done headers using CSS; for now they'll look like buttons since no styling has been added yet
- The list in the screenshot shows dot-points (again because of the 'no styling' thing... :joy:); keen to fix these up in the next ticket

### Helpful Links
Here are some resources I want to keep handy: 
- https://stackoverflow.com/questions/21949198/styling-html-text-without-css
- https://www.w3schools.com/html (basically everything on here)
- https://courses.cs.washington.edu/courses/cse154/17au/styleguide/html-css/naming-conventions-html.html
- Nice icon library to use for my buttons [here](https://ionic.io/ionicons)

I'll do some reading on the correct/ industry standard naming convention for `classes`(but probably a good idea to first figure out the [difference between `id` and `class`](https://www.w3schools.com/html/html_id.asp) 😂 ).

**Comment by marneylaunder** [comment]
Figured out I should stick to `class` when naming elements, since I want to style multiples of the same element the same way -  https://stackoverflow.com/questions/12889362/what-is-the-difference-between-id-and-class-in-css-and-when-should-i-use-them

**Comment by marneylaunder** [comment]
Good reference for styling the collapsible To Do and Done lists in a future story: https://www.w3schools.com/howto/tryit.asp?filename=tryhow_js_collapsible_symbol
